id: I8872F14C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T12:49:29+00:00'
last_modified: '2022-06-07T18:24:14.763770+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1991
  title: ཀློང་གསལ་སྙིང་པོའི་རྣམ་ཐར་མདོར་བསྡུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DA0C:
      image_group_id: I1CZ2025
      title: ''
      total_pages: 12
      order: 1
      base_file: DA0C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
